"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState,useTransition } from "react";
import { KeyRound, Plus, Save, ShieldCheck, Users } from "lucide-react";
import { createUserAction,updateUserAction } from "./admin-actions";

export function UsersAdminView({users,roles,branches}:{users:any[];roles:any[];branches:any[]}){
 const router=useRouter();const [pending,start]=useTransition();const [error,setError]=useState("");const [showNew,setShowNew]=useState(false);
 const [form,setForm]=useState({name:"",email:"",phone:"",password:"",roleId:roles[0]?.id||"",branchId:branches[0]?.id||""});
 function create(){setError("");start(async()=>{try{await createUserAction(form);setShowNew(false);setForm({name:"",email:"",phone:"",password:"",roleId:roles[0]?.id||"",branchId:branches[0]?.id||""});router.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear el usuario.")}})}
 function save(user:any,roleId:string,branchId:string,status:string,userStatus:string){setError("");start(async()=>{try{await updateUserAction({membershipId:user.membershipId,roleId,branchId:branchId||undefined,membershipStatus:status as any,userStatus:userStatus as any});router.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo actualizar el usuario.")}})}
 return <div className="page-stack"><section className="page-heading"><div><span className="eyebrow">ADMINISTRACIÓN</span><h1>Usuarios</h1><p>Personal de la empresa, rol asignado, sucursal predeterminada y estado de acceso.</p></div><div className="admin-heading-actions"><Link className="secondary-button" href="/administracion/roles"><ShieldCheck size={16}/> Roles y permisos</Link><button className="primary-button" onClick={()=>setShowNew(v=>!v)}><Plus size={16}/> Nuevo usuario</button></div></section>{error&&<div className="error-banner"><strong>No se pudo completar</strong><span>{error}</span></div>}
 {showNew&&<section className="panel admin-create-card"><div className="section-title"><div><h2>Crear usuario</h2><p>La contraseña se almacena cifrada y quedará preparada para el módulo de autenticación.</p></div><KeyRound size={19}/></div><div className="admin-form-grid"><label><span>Nombre completo</span><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label><span>Correo</span><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label><span>Celular</span><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label><span>Contraseña inicial</span><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label><span>Rol</span><select value={form.roleId} onChange={e=>setForm({...form,roleId:e.target.value})}>{roles.filter(r=>r.status==='ACTIVE').map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label><span>Sucursal predeterminada</span><select value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Sin sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label></div><button className="primary-button" disabled={pending} onClick={create}>{pending?"Creando...":"Crear usuario"}</button></section>}
 <section className="mobix-summary-grid four"><article><Users size={19}/><span>Usuarios</span><strong>{users.length}</strong></article><article><span className="summary-symbol">✓</span><span>Activos</span><strong>{users.filter(u=>u.status==='ACTIVE'&&u.userStatus==='ACTIVE').length}</strong></article><article><ShieldCheck size={19}/><span>Roles</span><strong>{roles.length}</strong></article><article><span className="summary-symbol">#</span><span>Sucursales</span><strong>{branches.length}</strong></article></section>
 <section className="panel table-panel"><div className="table-wrap"><table className="data-table admin-users-table"><thead><tr><th>Usuario</th><th>Rol</th><th>Sucursal</th><th>Membresía</th><th>Usuario</th><th>Acción</th></tr></thead><tbody>{users.map(user=><UserRow key={user.membershipId} user={user} roles={roles} branches={branches} pending={pending} onSave={save}/>)}</tbody></table></div></section></div>
}

function UserRow({user,roles,branches,pending,onSave}:{user:any;roles:any[];branches:any[];pending:boolean;onSave:(u:any,r:string,b:string,s:string,us:string)=>void}){
 const [role,setRole]=useState(user.roleId),[branch,setBranch]=useState(user.branchId||""),[status,setStatus]=useState(user.status),[userStatus,setUserStatus]=useState(user.userStatus);
 return <tr><td><div className="stacked-cell"><strong>{user.name}</strong><span>{user.email}{user.phone?` · ${user.phone}`:""}</span></div></td><td><select value={role} onChange={e=>setRole(e.target.value)}>{roles.filter(r=>r.status==='ACTIVE'||r.id===role).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></td><td><select value={branch} onChange={e=>setBranch(e.target.value)}><option value="">Sin sucursal</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></td><td><select value={status} onChange={e=>setStatus(e.target.value)}><option value="ACTIVE">Activo</option><option value="SUSPENDED">Suspendido</option><option value="INACTIVE">Inactivo</option></select></td><td><select value={userStatus} onChange={e=>setUserStatus(e.target.value)}><option value="ACTIVE">Activo</option><option value="SUSPENDED">Suspendido</option><option value="INACTIVE">Inactivo</option></select></td><td><button className="table-action-link" disabled={pending} onClick={()=>onSave(user,role,branch,status,userStatus)}><Save size={14}/> Guardar</button></td></tr>
}
