"use client";

import Link from "next/link";
import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, Boxes, Smartphone } from "lucide-react";
import { createTransferAction } from "./transfer-actions";

export function TransferForm({warehouses,products}:{warehouses:any[];products:any[]}){
 const router=useRouter(); const [pending,start]=useTransition(); const [error,setError]=useState("");
 const [from,setFrom]=useState(warehouses[0]?.id||""); const [to,setTo]=useState(warehouses[1]?.id||""); const [notes,setNotes]=useState("");
 const [selected,setSelected]=useState<Record<string,{checked:boolean;quantity:number;unitIds:string[]}>>({});
 const visible=useMemo(()=>products.map(p=>{const bal=p.balances.find((b:any)=>b.warehouseId===from);const units=p.units.filter((u:any)=>u.warehouseId===from);return {...p,available:p.type==="ACCESSORY"?Number(bal?.quantity||0):units.length,sourceUnits:units}}).filter(p=>p.available>0),[products,from]);
 function patch(id:string,data:any){setSelected(prev=>{const current=prev[id]??{checked:false,quantity:1,unitIds:[]};return {...prev,[id]:{...current,...data}}})}
 function toggleUnit(variantId:string,id:string,checked:boolean){const current=selected[variantId]||{checked:true,quantity:1,unitIds:[]};const ids=checked?[...current.unitIds,id]:current.unitIds.filter(x=>x!==id);patch(variantId,{checked:true,unitIds:ids,quantity:ids.length})}
 function submit(){setError("");const lines=visible.filter(p=>selected[p.variantId]?.checked).map(p=>({variantId:p.variantId,quantity:p.type==="ACCESSORY"?Number(selected[p.variantId]?.quantity||0):(selected[p.variantId]?.unitIds.length||0),unitIds:p.type==="ACCESSORY"?undefined:selected[p.variantId]?.unitIds})).filter(l=>l.quantity>0);start(async()=>{try{const r=await createTransferAction({fromWarehouseId:from,toWarehouseId:to,notes,lines});router.push(`/transferencias?created=${r.transferNumber}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:"No se pudo crear la transferencia.")}})}
 return <div className="page-stack"><section className="page-heading"><div><Link href="/transferencias" className="back-link"><ArrowLeft size={15}/> Volver</Link><span className="eyebrow">INVENTARIO</span><h1>Nueva transferencia</h1><p>Selecciona el inventario que saldrá del almacén origen.</p></div></section>{error&&<div className="error-banner"><strong>No se pudo transferir</strong><span>{error}</span></div>}
 <section className="panel transfer-route"><label><span>Almacén origen</span><select value={from} onChange={e=>{setFrom(e.target.value);setSelected({});const next=warehouses.find(w=>w.id!==e.target.value);if(to===e.target.value&&next)setTo(next.id)}}>{warehouses.map(w=><option key={w.id} value={w.id}>{w.branch} · {w.name}</option>)}</select></label><ArrowRight size={24}/><label><span>Almacén destino</span><select value={to} onChange={e=>setTo(e.target.value)}>{warehouses.filter(w=>w.id!==from).map(w=><option key={w.id} value={w.id}>{w.branch} · {w.name}</option>)}</select></label></section>
 <div className="transfer-layout"><section className="panel transfer-products"><div className="section-title"><div><h2>Inventario disponible</h2><p>{visible.length} variantes con existencia en origen</p></div><Boxes size={19}/></div><div className="transfer-product-list">{visible.map(p=>{const st=selected[p.variantId]||{checked:false,quantity:1,unitIds:[]};return <article key={p.variantId} className={st.checked?"selected":""}><div className="transfer-product-head"><input type="checkbox" checked={st.checked} onChange={e=>patch(p.variantId,{checked:e.target.checked})}/><span className="transfer-product-icon">{p.type==="ACCESSORY"?<Boxes size={17}/>:<Smartphone size={17}/>}</span><div><strong>{p.name}</strong><span>{p.brand} · {p.variant}</span><small>Disponible: {p.available}</small></div>{p.type==="ACCESSORY"&&<input className="transfer-qty" disabled={!st.checked} type="number" min="1" max={p.available} value={st.quantity} onChange={e=>patch(p.variantId,{quantity:Number(e.target.value)})}/>}</div>{p.type!=="ACCESSORY"&&st.checked&&<div className="transfer-unit-grid">{p.sourceUnits.map((u:any)=><label key={u.id}><input type="checkbox" checked={st.unitIds.includes(u.id)} onChange={e=>toggleUnit(p.variantId,u.id,e.target.checked)}/><code>{u.identifier}</code></label>)}</div>}</article>})}{!visible.length&&<div className="empty-table-state">El almacén origen no tiene inventario transferible.</div>}</div></section>
 <aside className="panel transfer-summary"><h2>Confirmar traslado</h2><label><span>Observación</span><textarea rows={5} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Motivo, transportista, referencia interna..."/></label><div className="transfer-summary-row"><span>Productos</span><strong>{Object.values(selected).filter(x=>x.checked).length}</strong></div><div className="transfer-summary-row"><span>Unidades</span><strong>{Object.values(selected).filter(x=>x.checked).reduce((s,x)=>s+(x.unitIds.length||Number(x.quantity||0)),0)}</strong></div><p>Al confirmar, los IMEI quedarán bloqueados como <strong>En transferencia</strong> hasta que el destino registre la recepción.</p><button className="primary-button wide" disabled={pending||from===to||warehouses.length<2} onClick={submit}>{pending?"Procesando...":"Enviar transferencia"}</button></aside></div></div>
}
