"use client";

import { useMemo,useState,useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, RotateCcw, Repeat2 } from "lucide-react";
import { createReturnAction } from "./return-actions";

const METHODS=[['CASH','Efectivo'],['YAPE','Yape'],['PLIN','Plin'],['CARD','Tarjeta'],['TRANSFER','Transferencia'],['CREDIT','Crédito'],['OTHER','Otro']];
function money(v:number){return new Intl.NumberFormat('es-PE',{style:'currency',currency:'PEN'}).format(v||0)}
export function ReturnForm({sales}:{sales:any[]}){
 const router=useRouter(); const [pending,start]=useTransition(); const [error,setError]=useState('');
 const [saleId,setSaleId]=useState(sales[0]?.id||''); const [type,setType]=useState<'RETURN'|'EXCHANGE'>('RETURN'); const [reason,setReason]=useState(''); const [method,setMethod]=useState('CASH'); const [notes,setNotes]=useState('');
 const sale=useMemo(()=>sales.find(s=>s.id===saleId),[sales,saleId]);
 const [selected,setSelected]=useState<Record<string,{checked:boolean;quantity:number;unitId?:string}>>({});
 const total=useMemo(()=>sale?.items.reduce((sum:number,item:any)=>{const st=selected[item.id];if(!st?.checked)return sum;const q=item.type==='PHONE'||item.type==='SERIALIZED'?1:Number(st.quantity||0);return sum+(item.total/item.quantity)*q},0)||0,[sale,selected]);
 function setLine(id:string,patch:any){setSelected(prev=>{const current=prev[id]??{checked:false,quantity:1};return {...prev,[id]:{...current,...patch}}})}
 function submit(){setError(''); const items=(sale?.items||[]).filter((i:any)=>selected[i.id]?.checked).map((i:any)=>({saleItemId:i.id,quantity:(i.type==='PHONE'||i.type==='SERIALIZED')?1:Number(selected[i.id]?.quantity||1),productUnitId:selected[i.id]?.unitId||undefined}));start(async()=>{try{const r=await createReturnAction({saleId,type,reason,refundMethod:type==='RETURN'?method:undefined,notes,items});router.push(`/devoluciones?created=${r.returnNumber}`);router.refresh()}catch(e){setError(e instanceof Error?e.message:'No se pudo registrar la operación.')}})}
 return <div className="page-stack"><section className="page-heading"><div><Link href="/devoluciones" className="back-link"><ArrowLeft size={15}/> Volver</Link><span className="eyebrow">DEVOLUCIONES Y CAMBIOS</span><h1>Nueva operación</h1><p>Selecciona la venta y el producto exacto que regresa a la tienda.</p></div></section>{error&&<div className="error-banner"><strong>No se pudo registrar</strong><span>{error}</span></div>}
 <section className="return-type-switch"><button className={type==='RETURN'?'active':''} onClick={()=>setType('RETURN')}><RotateCcw/><span><strong>Devolución</strong><small>Reingresa stock y devuelve el importe</small></span></button><button className={type==='EXCHANGE'?'active':''} onClick={()=>setType('EXCHANGE')}><Repeat2/><span><strong>Cambio</strong><small>Reingresa el producto y conserva el valor para el reemplazo</small></span></button></section>
 <div className="return-layout"><section className="panel return-main"><label className="field-label"><span>Venta original</span><select value={saleId} onChange={e=>{setSaleId(e.target.value);setSelected({})}}>{sales.map(s=><option key={s.id} value={s.id}>{s.saleNumber} · {s.customer} · {money(s.total)}</option>)}</select></label>{sale&&<><div className="return-sale-meta"><div><span>Cliente</span><strong>{sale.customer}</strong></div><div><span>Almacén</span><strong>{sale.warehouse}</strong></div><div><span>Venta</span><strong>{money(sale.total)}</strong></div></div><div className="return-items">{sale.items.map((item:any)=>{const remaining=item.quantity-item.returned, serialized=item.type==='PHONE'||item.type==='SERIALIZED', st=selected[item.id]||{checked:false,quantity:1};return <article className={st.checked?'selected':''} key={item.id}><input type="checkbox" disabled={remaining<=0} checked={!!st.checked} onChange={e=>setLine(item.id,{checked:e.target.checked})}/><div className="return-item-copy"><strong>{item.product}</strong><span>{item.variant}</span><small>Vendido {item.quantity} · Ya devuelto {item.returned} · Disponible {remaining}</small></div><div className="return-item-control">{serialized?<select disabled={!st.checked} value={st.unitId||''} onChange={e=>setLine(item.id,{unitId:e.target.value})}><option value="">Selecciona IMEI/serie</option>{item.units.filter((u:any)=>u.status==='SOLD').map((u:any)=><option key={u.id} value={u.id}>{u.identifier}</option>)}</select>:<input disabled={!st.checked} type="number" min="1" max={remaining} value={st.quantity} onChange={e=>setLine(item.id,{quantity:Number(e.target.value)})}/>}<strong>{money((item.total/item.quantity)*(serialized?1:Number(st.quantity||1)))}</strong></div></article>})}</div></>}</section>
 <aside className="panel return-summary"><h2>{type==='RETURN'?'Reembolso':'Valor del cambio'}</h2><label><span>Motivo *</span><textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Ej. equipo con falla dentro del periodo de cambio..."/></label>{type==='RETURN'&&<label><span>Medio de devolución</span><select value={method} onChange={e=>setMethod(e.target.value)}>{METHODS.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<label><span>Notas</span><textarea rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Observaciones internas..."/></label><div className="return-total"><span>{type==='RETURN'?'Total a devolver':'Valor reconocido'}</span><strong>{money(total)}</strong></div>{type==='EXCHANGE'&&<p className="return-help">Después de registrar el cambio, el producto vuelve al stock. El reemplazo se registra como una nueva venta en POS usando este valor como referencia comercial.</p>}<button className="primary-button wide" disabled={pending||total<=0} onClick={submit}>{pending?'Registrando...':'Confirmar operación'}</button></aside></div></div>
}
